// Angular/src/app/GroupRowSelection/group-row-component/group-row.component.ts
import { Component, Input, Output, EventEmitter, AfterViewInit } from '@angular/core';
import { DxCheckBoxTypes } from 'devextreme-angular/ui/check-box';
import { DxDataGridTypes } from "devextreme-angular/ui/data-grid";

@Component({
  selector: 'group-row-selectable',
  templateUrl: './group-row.component.html',
  styleUrls: ['./group-row.component.css'],
})
export class GroupRowComponent implements AfterViewInit {
  @Input() groupCellData!: DxDataGridTypes.ColumnGroupCellTemplateData;
  @Input() childRowKeys: any[] | undefined = [];
  @Output() onInitialized = new EventEmitter<IGroupRowReadyParameter>();
  isLoading: boolean = true;
  checked: boolean | undefined = false;
  childKeys!: any[];
  iconSize: number = 18;
  constructor() {
    this.checkBoxValueChanged = this.checkBoxValueChanged.bind(this);
  }
  ngAfterViewInit() {
    this.onInitialized.emit({ key: this.groupCellData.row.key, component: this });
  }
  checkBoxValueChanged(e: DxCheckBoxTypes.ValueChangedEvent) {
    this.checked = e.value;
    if (e.value)
      this.groupCellData.component.selectRows(this.childRowKeys ?? [], true);
    else
      this.groupCellData.component.deselectRows(this.childRowKeys ?? []);
  }
  public setCheckedState(value: boolean | undefined) {
    this.checked = value;
    this.isLoading = false;
  }
}
export interface IGroupRowReadyParameter {
  key: string[];
  component: GroupRowComponent;
}
<div class="group-row-flex">
  <div class="group-selection-front">
    <dx-load-indicator [height]="iconSize" [width]="iconSize" [visible]="isLoading"></dx-load-indicator>
    <dx-check-box *ngIf="!isLoading" [iconSize]="iconSize" [value]="checked" (onValueChanged)="checkBoxValueChanged($event)"></dx-check-box>
  </div>
  <span>{{ groupCellData | groupText }}</span>
</div>

// React/src/GroupRowSelection/GroupRowComponent.tsx
import { LoadIndicator } from 'devextreme-react';
import './GroupRowComponent.css';
import { DataGridTypes } from 'devextreme-react/data-grid';
import { useCallback, useEffect, useState } from 'react';
import CheckBox from 'devextreme-react/check-box';

interface GroupRowProps {
  groupCellData: DataGridTypes.ColumnGroupCellTemplateData;
  childRowKeys?: any[];
  onInitialized: (param: IGroupRowReadyParameter) => void;
}

const iconSize = 18;

const GroupRowComponent: React.FC<GroupRowProps> = ({
  groupCellData,
  onInitialized,
}) => {
  const [isLoading, setIsLoading] = useState(true);
  const [checked, setChecked] = useState<boolean | undefined>(false);
  const [childKeys, setChildKeys] = useState<any>([]);

  const onValueChange = useCallback((value: boolean | null) => {
    if (value) {
      groupCellData.component.selectRows(childKeys ?? [], true);
    } else {
      groupCellData.component.deselectRows(childKeys ?? []);
    }
  }, [childKeys, groupCellData]);

  const setCheckedState = useCallback((value: boolean | undefined) => {
    setChecked(value);
    setIsLoading(false);
  }, [setChecked, setIsLoading]);

  useEffect(() => {
    const arr = onInitialized({ key: groupCellData.row.key, setCheckedState: setCheckedState.bind(this) });
    (arr as unknown as Promise<any>).then((children: any) => {
      setChildKeys(children);
    });
  }, [groupCellData, setCheckedState, setChildKeys]);

  return (
    <div className="group-row-flex">
      <div className="group-selection-front">
        <LoadIndicator
          height={iconSize}
          width={iconSize}
          visible={isLoading}></LoadIndicator>
        <CheckBox
          visible={!isLoading}
          iconSize={iconSize}
          value={checked}
          onValueChange={onValueChange}
        ></CheckBox>
      </div>
      <span>{groupCellData.text}</span>
    </div>
  );
};

export default GroupRowComponent;

export interface IGroupRowReadyParameter {
  key: string[];
  setCheckedState: Function;
}
