// Angular/src/app/GroupRowSelection/group-row-component/group-row.component.ts
import { Component, Input, Output, EventEmitter, AfterViewInit } from '@angular/core';
import { DxCheckBoxTypes } from 'devextreme-angular/ui/check-box';
import { DxDataGridTypes } from "devextreme-angular/ui/data-grid";

@Component({
  selector: 'group-row-selectable',
  templateUrl: './group-row.component.html',
  styleUrls: ['./group-row.component.css'],
})
export class GroupRowComponent implements AfterViewInit {
  @Input() groupCellData!: DxDataGridTypes.ColumnGroupCellTemplateData;
  @Input() childRowKeys: any[] | undefined = [];
  @Output() onInitialized = new EventEmitter<IGroupRowReadyParameter>();
  isLoading: boolean = true;
  checked: boolean | undefined = false;
  childKeys!: any[];
  iconSize: number = 18;
  constructor() {
    this.checkBoxValueChanged = this.checkBoxValueChanged.bind(this);
  }
  ngAfterViewInit() {
    this.onInitialized.emit({ key: this.groupCellData.row.key, component: this });
  }
  checkBoxValueChanged(e: DxCheckBoxTypes.ValueChangedEvent) {
    this.checked = e.value;
    if (e.value)
      this.groupCellData.component.selectRows(this.childRowKeys ?? [], true);
    else
      this.groupCellData.component.deselectRows(this.childRowKeys ?? []);
  }
  public setCheckedState(value: boolean | undefined) {
    this.checked = value;
    this.isLoading = false;
  }
}
export interface IGroupRowReadyParameter {
  key: string[];
  component: GroupRowComponent;
}
<div class="group-row-flex">
  <div class="group-selection-front">
    <dx-load-indicator [height]="iconSize" [width]="iconSize" [visible]="isLoading"></dx-load-indicator>
    <dx-check-box *ngIf="!isLoading" [iconSize]="iconSize" [value]="checked" (onValueChanged)="checkBoxValueChanged($event)"></dx-check-box>
  </div>
  <span>{{ groupCellData | groupText }}</span>
</div>

// Vue/src/components/GroupRowSelection/GroupRowComponent.vue
<script setup lang="ts">
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import DxCheckBox, { type DxCheckBoxTypes } from 'devextreme-vue/check-box';
import type { DxDataGridTypes } from 'devextreme-vue/data-grid';
import { onMounted, defineEmits } from 'vue';

const props = defineProps<{
  groupCellData: any,
  childRowKeys: any,
  // onInitialized: EventEmitter,
}>();

const emit = defineEmits(['initGroupRow']);

const iconSize = 18;

let isLoading = true;
let checked: boolean|undefined = false;
let childKeys: any[] = [];

onMounted(() => {
  // props.onInitialized.emit('event');
  emit("initGroupRow", [props.groupCellData.row.key, setCheckedState.bind(this)])
});

function checkBoxValueChanged(e: DxCheckBoxTypes.ValueChangedEvent) {
    checked = e.value;
    if (e.value) { 
      props.groupCellData.component.selectRows(props.childRowKeys ?? [], true);
    } else {
      props.groupCellData.component.deselectRows(props.childRowKeys ?? []);
    }
}

function setCheckedState(value:any){
  isLoading = false;
  checked = value;
}

</script>

<template>
  <div class="group-row-flex">
    <div class="group-selection-front">
      <dx-load-indicator :height="iconSize" :width="iconSize" :visible="isLoading"></dx-load-indicator>
      <dx-check-box v-if="!isLoading" :iconSize="iconSize" :value="checked" @onValueChanged="checkBoxValueChanged"></dx-check-box>
    </div>
    <!-- <span>{{ groupCellData | groupText }}</span> -->
  </div>
</template>

<style scoped>
.group-selection-front {
  margin-right: 10px;
}
.group-selection-front .dx-loadindicator {
  display: block;
}
.group-row-flex {
  display: flex;
  flex-direction: row;
  align-items: center;
}
</style>
